# Generated by Django 2.1.1 on 2018-09-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cargo_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
