# Generated by Django 2.1.1 on 2018-09-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_veiculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
