# Generated by Django 2.1.1 on 2018-09-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_locacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacao',
            options={'verbose_name_plural': 'Locações'},
        ),
    ]
