# Generated by Django 2.1.1 on 2018-09-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180916_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('A', 'Em Aberto'), ('F', 'Fechada')], max_length=3),
        ),
    ]
