# Generated by Django 2.1.1 on 2018-09-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180916_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('FECHADA', 'Fechada')], max_length=10),
        ),
    ]
