# Generated by Django 2.1.1 on 2018-09-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180916_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoVeiculo',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('CUPE', 'Cupe'), ('CROSSOVER', 'Crossover'), ('ESPORTIVO', 'Esportivo'), ('HATCH', 'Hacth'), ('JIPE', 'Jipe'), ('PICAPE', 'Picape'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN E MINIVAM', 'Van/Minivam')], max_length=15),
        ),
    ]
