# Generated by Django 2.1.1 on 2018-09-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180916_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('LOCADO', 'Ativo'), ('DISPONÍVEL', 'Disponível'), ('INDISPONÍVEL', 'Indisponível')], max_length=20),
        ),
    ]
